table ___Combined_Outreach_All
	lineageTag: 753d11b5-040d-4b09-b4f4-fd8b71b2e560

	measure DateInPrevMonth = ```
			
			VAR PrevMonthNum       = MONTH ( TODAY() ) - 1
			VAR PrevYearAdjustment = IF ( PrevMonthNum = 0, 1, 0 )
			VAR PrevYear           = YEAR ( TODAY() ) - PrevYearAdjustment
			VAR PrevMonth          = IF ( PrevMonthNum = 0, 12, PrevMonthNum )
			VAR StartDate          = DATE ( PrevYear, PrevMonth, 1 )
			VAR EndDate            = EOMONTH ( StartDate, 0 )
			RETURN
			    IF (
			        MIN ( '___Combined_Outreach_All'[Date] ) >= StartDate
			            && MAX ( '___Combined_Outreach_All'[Date] ) <= EndDate,
			        1,
			        0
			    )
			
			```
		formatString: 0
		lineageTag: 70737782-f54c-4056-9d85-04ca9ba87368

	measure SubtitlePrevMonth = ```
			
			VAR MinD = MIN( '___Combined_Outreach_All'[Date] )
			RETURN
			    IF(
			        NOT ISBLANK( MinD ),
			        FORMAT( MinD, "MMMM yyyy" ),
			        ""
			    )
			
			```
		lineageTag: 179369e4-d47e-4126-862d-a24951ded0cf

	measure 'Engagement Title' = ```
			
			"Engagement Initiatives by Bureau"
			
			```
		lineageTag: 4b7e84be-4903-4d3d-8010-ec48f2054c50

	measure 'Engagement Subtitle' = ```
			
			'UI'[UI PrevMonth Label]   -- e.g., "October 2025" on Nov 2, 2025
			
			```
		lineageTag: 8b353243-42e4-4f4e-9657-5c6df05edca6

	measure 'Prev Month Flag' =
			
			VAR StartPrev =
			    EOMONTH ( TODAY(), -2 ) + 1        -- first day of the prior month
			VAR EndPrev =
			    EOMONTH ( TODAY(), -1 )            -- last day of the prior month
			RETURN
			    IF (
			        MIN ( 'preview_table'[Date] ) >= StartPrev
			            && MAX ( 'preview_table'[Date] ) <= EndPrev,
			        1,
			        0
			    )
		lineageTag: fcc69c01-0cb2-4228-9664-14cf27d53c40

	column IsPrevMonth = ```
			
			VAR PrevMonthNum       = MONTH ( TODAY() ) - 1
			VAR PrevYearAdjustment = IF ( PrevMonthNum = 0, 1, 0 )
			VAR PrevYear           = YEAR ( TODAY() ) - PrevYearAdjustment
			VAR PrevMonth          = IF ( PrevMonthNum = 0, 12, PrevMonthNum )
			VAR StartDate          = DATE ( PrevYear, PrevMonth, 1 )
			VAR EndDate            = EOMONTH ( StartDate, 0 )
			RETURN
			    IF(
			        '___Combined_Outreach_All'[Date] >= StartDate
			            && '___Combined_Outreach_All'[Date] <= EndDate,
			        TRUE(),
			        FALSE()
			    )
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ba1515b7-5633-49d4-a9d2-f51324711dff
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column DateDisplay = ```
			FORMAT( '___Combined_Outreach_All'[Date], "MM/dd/yyyy" )
			
			```
		lineageTag: db85e4ed-5b2e-41f6-8175-421754ba276f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3733b77-694e-4851-b2e2-996f4c2e9866
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 3f57bc3d-de1b-4ada-91cc-3a03185263f6
			defaultHierarchy: LocalDateTable_a92b67c9-2529-42b5-8346-6475d25fa653.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Event Duration (Hours)'
		dataType: double
		lineageTag: 04e97106-8971-47e8-9bec-c52a0e3f1b00
		summarizeBy: sum
		sourceColumn: Event Duration (Hours)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Event Name'
		dataType: string
		lineageTag: fcdecffb-4a09-4426-8cc4-908010c250a7
		summarizeBy: none
		sourceColumn: Event Name

		annotation SummarizationSetBy = Automatic

	column 'Location of Event'
		dataType: string
		lineageTag: f6aeeea7-aa2e-4046-9396-9bc678b1fb5d
		summarizeBy: none
		sourceColumn: Location of Event

		annotation SummarizationSetBy = Automatic

	column 'Number of Police Department Attendees'
		dataType: int64
		formatString: 0
		lineageTag: 5272e8f2-cc7d-4761-8550-4caf0f59607d
		summarizeBy: sum
		sourceColumn: Number of Police Department Attendees

		annotation SummarizationSetBy = Automatic

	column Office
		dataType: string
		lineageTag: eeeea241-a25d-4bc3-8ba8-204e2221b1e9
		summarizeBy: none
		sourceColumn: Office

		annotation SummarizationSetBy = Automatic

	column 'Prev Month Flag Column' =
			
			VAR StartPrev = EOMONTH ( TODAY(), -2 ) + 1
			VAR EndPrev = EOMONTH ( TODAY(), -1 )
			RETURN IF ( '___Combined_Outreach_All'[Date] >= StartPrev && '___Combined_Outreach_All'[Date].[Date] <= EndPrev, 1, 0 )
		formatString: 0
		lineageTag: 2569366f-00d7-4d07-ad42-416452394600
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition ___Combined_Outreach_All = m
		mode: import
		source = ```
				// 🐍 Combined_Outreach_All — Using Python ETL Output
				// Simplified M code that reads from centralized Python ETL CSV output
				// Maintains exact same column structure for Power BI compatibility
				let
				    // === 1. Dynamic File Path Discovery ===
				    // Look for the most recent Python ETL output file
				    OutputFolder = "C:\Users\carucci_r\OneDrive - City of Hackensack\02_ETL_Scripts\Community_Engagment\output\",
				    
				    // Try to find the most recent community_engagement_data_*.csv file
				    // Pattern: community_engagement_data_YYYYMMDD_HHMMSS.csv
				    PythonETLFile = try 
				        let
				            // Get all CSV files in the output directory
				            Source = Folder.Files(OutputFolder),
				            FilteredFiles = Table.SelectRows(Source, each Text.StartsWith([Name], "community_engagement_data_") and Text.EndsWith([Name], ".csv")),
				            SortedFiles = Table.Sort(FilteredFiles, {{"Date modified", Order.Descending}}),
				            LatestFile = if Table.RowCount(SortedFiles) > 0 
				                        then OutputFolder & SortedFiles{0}[Name]
				                        else error "No Python ETL output files found"
				        in
				            LatestFile
				    otherwise
				        // Fallback to a specific filename pattern if dynamic discovery fails
				        OutputFolder & "community_engagement_combined_" & Date.ToText(DateTime.Date(DateTime.LocalNow()), "yyyy-MM-dd") & ".csv",
				
				    // === 2. Read Python ETL CSV Output ===
				    CSVSource = Csv.Document(File.Contents(PythonETLFile), [Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    HeadersPromoted = Table.PromoteHeaders(CSVSource, [PromoteAllScalars=true]),
				    
				    // === 3. Data Type Transformations ===
				    // Handle datetime strings from Python ETL (format: "YYYY-MM-DD HH:MM:SS")
				    DateParsed = Table.TransformColumns(HeadersPromoted, {
				        {"date", each 
				            if _ = null or _ = "" 
				            then null 
				            else try DateTime.Date(DateTime.FromText(_)) otherwise Date.FromText(Text.Start(_, 10)), 
				        type date}
				    }),
				    
				    // Handle time columns safely (may be in various formats from Python)
				    TimeParsed = Table.TransformColumns(DateParsed, {
				        {"start_time", each try Time.FromText(_) otherwise null, type time},
				        {"end_time", each try Time.FromText(_) otherwise null, type time}
				    }),
				    
				    TypedData = Table.TransformColumnTypes(TimeParsed, {
				        {"event_name", type text},
				        {"location", type text},
				        {"duration_hours", type number},
				        {"attendee_count", Int64.Type},
				        {"office", type text},
				        {"division", type text}
				    }),
				    
				    // Handle any duration_hours conversion issues (Python ETL may have NaNs)
				    SafeDuration = Table.TransformColumns(TypedData, {
				        {"duration_hours", each 
				            if _ = null or _ = "" or Text.From(_) = "nan" 
				            then 0.5 
				            else try Number.From(_) otherwise 0.5, type number}
				    }),
				    
				    // Handle any attendee_count conversion issues  
				    SafeAttendees = Table.TransformColumns(SafeDuration, {
				        {"attendee_count", each try Number.From(_) otherwise 1, Int64.Type}
				    }),
				    
				    // === 4. Column Selection and Renaming ===
				    // Select only the columns needed for Power BI
				    SelectedColumns = Table.SelectColumns(SafeAttendees, {
				        "date",
				        "duration_hours", 
				        "event_name",
				        "location",
				        "attendee_count",
				        "office"
				    }),
				    
				    // Rename columns to match exact Power BI expectations
				    RenamedColumns = Table.RenameColumns(SelectedColumns, {
				        {"date", "Date"},
				        {"duration_hours", "Event Duration (Hours)"},
				        {"event_name", "Event Name"}, 
				        {"location", "Location of Event"},
				        {"attendee_count", "Number of Police Department Attendees"},
				        {"office", "Office"}
				    }),
				    
				    // === 5. Data Quality and Filtering ===
				    // Remove rows with null dates (same as original M code)
				    FilteredData = Table.SelectRows(RenamedColumns, each [Date] <> null),
				    
				    // Ensure Event Duration is reasonable (0.1 to 24 hours)
				    ValidatedDuration = Table.TransformColumns(FilteredData, {
				        {"Event Duration (Hours)", each 
				            if _ = null or _ <= 0 then 0.5
				            else if _ > 24 then 8.0  
				            else Number.Round(_, 2), 
				        type number}
				    }),
				    
				    // Ensure attendee count is at least 1 if null/zero
				    ValidatedAttendees = Table.TransformColumns(ValidatedDuration, {
				        {"Number of Police Department Attendees", each 
				            if _ = null or _ <= 0 then 1 else _, 
				        Int64.Type}
				    }),
				    
				    // === 6. Final Sort and Output ===
				    // Sort by date ascending (same as original M code)
				    FinalData = if Table.RowCount(ValidatedAttendees) > 0 
				                then Table.Sort(ValidatedAttendees, {{"Date", Order.Ascending}}) 
				                else ValidatedAttendees
				
				in
				    FinalData
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

