table ___Combined_Outreach_All
	lineageTag: 753d11b5-040d-4b09-b4f4-fd8b71b2e560

	measure 'measure SubtitlePrevMonth' = ```
			
						
						VAR MinD = MIN ( '___Combined_Outreach_All'[Date] )
						RETURN
						    IF (
						        NOT ISBLANK ( MinD ),
						        "Tracking community outreach and engagement initiatives by bureau | "
						            & FORMAT ( MinD, "MMMM yyyy" ),
						        "Tracking community outreach and engagement initiatives by bureau"
						    )
			```
		lineageTag: 179369e4-d47e-4126-862d-a24951ded0cf

	measure 'Engagement Title' = ```
			
			"Engagement Initiatives by Bureau"
			
			```
		lineageTag: 4b7e84be-4903-4d3d-8010-ec48f2054c50

	/// Dynamic subtitle using actual data range instead of TODAY(). Reflects pReportMonth-driven M code window.
	measure 'Engagement Subtitle' =
			VAR MaxDate = MAX('___Combined_Outreach_All'[Date])
			VAR MinDate = MIN('___Combined_Outreach_All'[Date])
			RETURN
			"Tracking community outreach and engagement initiatives by bureau. " &
			"Rolling 13-Month Overview (" &
			    FORMAT(MinDate, "MMMM yyyy") & " - " & FORMAT(MaxDate, "MMMM yyyy") & ")"
		lineageTag: 8b353243-42e4-4f4e-9657-5c6df05edca6

	/// Count of outreach sessions in the report month, using ___DimMonth bridge. Updated 2026-03-25.
	measure 'Outreach Sessions' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR MonthEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        COUNTROWS ( '___Combined_Outreach_All' ),
			        '___Combined_Outreach_All'[Date] >= ReportMonthStart,
			        '___Combined_Outreach_All'[Date] <= MonthEnd
			    )
		formatString: #,0
		displayFolder: Summary
		lineageTag: dadfd36f-e25e-4aed-90ab-cedced4aebd8

	/// Total event hours in the report month, using ___DimMonth bridge. Updated 2026-03-25.
	measure 'Outreach Total Hours' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR MonthEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        SUM ( '___Combined_Outreach_All'[Event Duration (Hours)] ),
			        '___Combined_Outreach_All'[Date] >= ReportMonthStart,
			        '___Combined_Outreach_All'[Date] <= MonthEnd
			    )
		formatString: #,0.0
		displayFolder: Summary
		lineageTag: 9ef45900-6504-48c3-b036-d8461de1af0a

	/// Total PD attendees in the report month, using ___DimMonth bridge. Updated 2026-03-25.
	measure 'Outreach Total Attendees' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR MonthEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        SUM ( '___Combined_Outreach_All'[Number of Police Department Attendees] ),
			        '___Combined_Outreach_All'[Date] >= ReportMonthStart,
			        '___Combined_Outreach_All'[Date] <= MonthEnd
			    )
		formatString: #,0
		displayFolder: Summary
		lineageTag: 1b3ca607-2fb0-469e-b206-797baa6b4c3f

	/// Total community outreach events YTD using ___DimMonth bridge.
	measure 'Outreach Events YTD' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR YtdStart = DATE ( YEAR ( ReportMonthStart ), 1, 1 )
			VAR YtdEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        COUNTROWS ( '___Combined_Outreach_All' ),
			        '___Combined_Outreach_All'[Date] >= YtdStart,
			        '___Combined_Outreach_All'[Date] <= YtdEnd
			    )
		formatString: #,0
		displayFolder: Summary
		lineageTag: d04972b8-ef58-41f4-baa4-9a227b1ac203

	/// Total outreach hours YTD.
	measure 'Outreach Hours YTD' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR YtdStart = DATE ( YEAR ( ReportMonthStart ), 1, 1 )
			VAR YtdEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        SUM ( '___Combined_Outreach_All'[Event Duration (Hours)] ),
			        '___Combined_Outreach_All'[Date] >= YtdStart,
			        '___Combined_Outreach_All'[Date] <= YtdEnd
			    )
		displayFolder: Summary
		lineageTag: 24f42562-1a49-47bd-b9cc-c542a234ddff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Total PD attendees at outreach events YTD.
	measure 'Outreach Attendees YTD' =
			
			VAR ReportMonthStart = MAX ( '___DimMonth'[MonthStart] )
			VAR YtdStart = DATE ( YEAR ( ReportMonthStart ), 1, 1 )
			VAR YtdEnd = EOMONTH ( ReportMonthStart, 0 )
			RETURN
			    CALCULATE (
			        SUM ( '___Combined_Outreach_All'[Number of Police Department Attendees] ),
			        '___Combined_Outreach_All'[Date] >= YtdStart,
			        '___Combined_Outreach_All'[Date] <= YtdEnd)
		formatString: #,0
		displayFolder: Summary
		lineageTag: bc4a3580-f0df-438a-9bba-07e2ea2090ff

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 04d8dac6-5001-4b63-8540-df35fa4c7ea1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fb7c4c3e-c5a3-43fb-b11e-1aacaaca8b54
			defaultHierarchy: LocalDateTable_21720304-fb4b-477e-b055-ce01af18a0ef.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Event Duration (Hours)'
		dataType: double
		lineageTag: a41eb847-0692-481a-b04c-bca01d647532
		summarizeBy: sum
		sourceColumn: Event Duration (Hours)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Event Name'
		dataType: string
		lineageTag: 0ced9bd0-864b-4b1f-aa1e-26cb3cf66ab7
		summarizeBy: none
		sourceColumn: Event Name

		annotation SummarizationSetBy = Automatic

	column 'Location of Event'
		dataType: string
		lineageTag: 5d7f2c31-4e09-46d3-9565-234f56aa0ca8
		summarizeBy: none
		sourceColumn: Location of Event

		annotation SummarizationSetBy = Automatic

	column 'Number of Police Department Attendees'
		dataType: int64
		formatString: 0
		lineageTag: 01283d8b-c4e3-4928-974a-6ff8d49a9093
		summarizeBy: sum
		sourceColumn: Number of Police Department Attendees

		annotation SummarizationSetBy = Automatic

	column Office
		dataType: string
		lineageTag: b7917414-e0b7-41a1-8a7d-f8e213514354
		summarizeBy: none
		sourceColumn: Office

		annotation SummarizationSetBy = Automatic

	partition ___Combined_Outreach_All = m
		mode: import
		source = ```
				// 🕒 2026-03-25-12-00-00 (EST)
				// # community/___Combined_Outreach_All.m
				// # Author: R. A. Carucci
				// # Purpose: Load community engagement data from latest Python ETL export (.csv or .xlsx) for Power BI.
				
				let
				    ReportMonth = pReportMonth,
				
				    // === 1. Dynamic File Path Discovery ===
				    // ETL writes BOTH community_engagement_data_*.csv and *.xlsx (same timestamp). If a run only
				    // leaves xlsx (or xlsx is newer on disk), picking "latest CSV only" loads a STALE file (e.g. Jan
				    // CSV while Feb xlsx exists) — YTD/months look wrong. Use newest file by Date modified: .csv OR .xlsx.
				    OutputFolder = "C:\Users\carucci_r\OneDrive - City of Hackensack\02_ETL_Scripts\Community_Engagement\output\",
				    
				    Source = Folder.Files(OutputFolder),
				    FilteredFiles = Table.SelectRows(Source, each 
				        Text.StartsWith([Name], "community_engagement_data_") 
				        and (
				            Text.EndsWith(Text.Lower([Name]), ".csv") 
				            or Text.EndsWith(Text.Lower([Name]), ".xlsx")
				        )
				    ),
				    SortedFiles = Table.Sort(FilteredFiles, {{"Date modified", Order.Descending}}),
				    PythonETLFile = if Table.RowCount(SortedFiles) > 0 
				        then OutputFolder & SortedFiles{0}[Name]
				        else error "No community_engagement_data_*.csv or *.xlsx in output folder",
				    FileExt = Text.Lower(Text.AfterDelimiter(PythonETLFile, ".", {0, RelativePosition.FromEnd})),
				
				    // === 2. Read Python ETL output (CSV or Excel) ===
				    HeadersPromoted = if FileExt = "csv" then
				        let
				            CSVSource = Csv.Document(File.Contents(PythonETLFile), [Delimiter=",", Columns=null, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				            H = Table.PromoteHeaders(CSVSource, [PromoteAllScalars=true])
				        in
				            H
				    else if FileExt = "xlsx" then
				        let
				            RawWB = Excel.Workbook(File.Contents(PythonETLFile), null, true),
				            SheetRows = Table.SelectRows(RawWB, each [Kind] = "Sheet" and [Item] = "Combined_Data"),
				            DataOnly = if Table.RowCount(SheetRows) > 0 then SheetRows{0}[Data] else error "Sheet Combined_Data not found in " & PythonETLFile,
				            H = Table.PromoteHeaders(DataOnly, [PromoteAllScalars=true])
				        in
				            H
				    else
				        error "Unsupported outreach export extension: " & FileExt,
				    
				    // === 3. Data Type Transformations ===
				    // CSV often has text dates; Excel may return date, datetime, or serial — normalize to date.
				    DateParsed = Table.TransformColumns(HeadersPromoted, {
				        {"date", each 
				            if _ = null or _ = "" then null
				            else if _ is date then _
				            else if _ is datetime then Date.From(_)
				            else if _ is number then Date.AddDays(#date(1899, 12, 30), Number.From(_))
				            else try DateTime.Date(DateTime.FromText(Text.From(_))) otherwise Date.FromText(Text.Start(Text.From(_), 10)), 
				        type date}
				    }),
				    
				    // Handle time columns safely (may be in various formats from Python)
				    TimeParsed = Table.TransformColumns(DateParsed, {
				        {"start_time", each try Time.FromText(_) otherwise null, type time},
				        {"end_time", each try Time.FromText(_) otherwise null, type time}
				    }),
				    
				    TypedData = Table.TransformColumnTypes(TimeParsed, {
				        {"event_name", type text},
				        {"location", type text},
				        {"duration_hours", type number},
				        {"attendee_count", Int64.Type},
				        {"office", type text},
				        {"division", type text}
				    }),
				    
				    // Handle any duration_hours conversion issues (Python ETL may have NaNs)
				    SafeDuration = Table.TransformColumns(TypedData, {
				        {"duration_hours", each 
				            if _ = null or _ = "" or Text.From(_) = "nan" 
				            then 0.5 
				            else try Number.From(_) otherwise 0.5, type number}
				    }),
				    
				    // Handle any attendee_count conversion issues  
				    SafeAttendees = Table.TransformColumns(SafeDuration, {
				        {"attendee_count", each try Number.From(_) otherwise 1, Int64.Type}
				    }),
				    
				    // === 4. Column Selection and Renaming ===
				    // Select only the columns needed for Power BI
				    SelectedColumns = Table.SelectColumns(SafeAttendees, {
				        "date",
				        "duration_hours", 
				        "event_name",
				        "location",
				        "attendee_count",
				        "office"
				    }),
				    
				    // Rename columns to match exact Power BI expectations
				    RenamedColumns = Table.RenameColumns(SelectedColumns, {
				        {"date", "Date"},
				        {"duration_hours", "Event Duration (Hours)"},
				        {"event_name", "Event Name"}, 
				        {"location", "Location of Event"},
				        {"attendee_count", "Number of Police Department Attendees"},
				        {"office", "Office"}
				    }),
				    
				    // === 5. Data Quality and Filtering ===
				    // Remove rows with null dates (same as original M code)
				    FilteredData = Table.SelectRows(RenamedColumns, each [Date] <> null),
				    
				    // Ensure Event Duration is reasonable (0.1 to 24 hours)
				    ValidatedDuration = Table.TransformColumns(FilteredData, {
				        {"Event Duration (Hours)", each 
				            if _ = null or _ <= 0 then 0.5
				            else if _ > 24 then 8.0  
				            else Number.Round(_, 2), 
				        type number}
				    }),
				    
				    // Ensure attendee count is at least 1 if null/zero
				    ValidatedAttendees = Table.TransformColumns(ValidatedDuration, {
				        {"Number of Police Department Attendees", each 
				            if _ = null or _ <= 0 then 1 else _, 
				        Int64.Type}
				    }),
				    
				    // === 6. Final Sort and Output ===
				    // Sort by date ascending (same as original M code)
				    FinalData = if Table.RowCount(ValidatedAttendees) > 0 
				                then Table.Sort(ValidatedAttendees, {{"Date", Order.Ascending}}) 
				                else ValidatedAttendees,
				    #"Sorted Rows" = Table.Sort(FinalData,{{"Date", Order.Descending}})
				
				in
				    #"Sorted Rows"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

