table ___Cost_of_Training
	lineageTag: cafb1bb0-2434-4e03-afc2-3aa7041ca503

	measure 'Subtitle - Training Cost by Delivery Method' =
			VAR EndDate = CALCULATE(MAX(___DimMonth[MonthStart]), ALL(___DimMonth))
			VAR StartDate = CALCULATE(MIN(___DimMonth[MonthStart]), ALL(___DimMonth))
			RETURN
			"Tracking training program costs by delivery method. " &
			"Rolling 13-Month Overview (" &
			    FORMAT(StartDate, "MMMM yyyy") & " - " & FORMAT(EndDate, "MMMM yyyy") & ")"
		lineageTag: ad8076b1-df1e-45eb-948c-38ae074add50

	/// In-Person training cost YTD from Cost_of_Training table.
	measure 'Training In-Person YTD' =
			VAR ReportMonthStart = MAX('___DimMonth'[MonthStart])
			VAR YtdYear = YEAR(ReportMonthStart)
			VAR YtdMonth = MONTH(ReportMonthStart)
			VAR YtdStartSort = YtdYear * 100 + 1
			VAR YtdEndSort = YtdYear * 100 + YtdMonth
			RETURN
			    CALCULATE(
			        SUM('___Cost_of_Training'[Cost]),
			        '___Cost_of_Training'[Delivery_Type] = "In-Person",
			        '___Cost_of_Training'[Period_Sort] >= YtdStartSort,
			        '___Cost_of_Training'[Period_Sort] <= YtdEndSort
			    )
		formatString: $#,0
		displayFolder: Training YTD
		lineageTag: fc55169a-f54d-4d63-9156-adf1f5cdd574

	/// Online training cost YTD from Cost_of_Training table.
	measure 'Training Online YTD' =
			VAR ReportMonthStart = MAX('___DimMonth'[MonthStart])
			VAR YtdYear = YEAR(ReportMonthStart)
			VAR YtdMonth = MONTH(ReportMonthStart)
			VAR YtdStartSort = YtdYear * 100 + 1
			VAR YtdEndSort = YtdYear * 100 + YtdMonth
			RETURN
			    CALCULATE(
			        SUM('___Cost_of_Training'[Cost]),
			        '___Cost_of_Training'[Delivery_Type] = "Online",
			        '___Cost_of_Training'[Period_Sort] >= YtdStartSort,
			        '___Cost_of_Training'[Period_Sort] <= YtdEndSort
			    )
		formatString: $#,0
		displayFolder: Training YTD
		lineageTag: db0f63c4-fe08-4ae9-94f0-ec1bfb2ba0fc

	column Delivery_Type
		dataType: string
		lineageTag: 6b4aff26-3e55-4edb-870b-21f738db8df5
		summarizeBy: none
		sourceColumn: Delivery_Type

		annotation SummarizationSetBy = Automatic

	column Total
		dataType: double
		lineageTag: f9d50105-7c51-4828-9025-8bcbb35390c8
		summarizeBy: sum
		sourceColumn: Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period
		dataType: string
		lineageTag: d31ce6f8-4207-4b0e-92df-38919a89c32a
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: Period_Sort

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		lineageTag: 2241a676-4a77-4f46-8404-002d4d147432
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Period_Sort
		dataType: int64
		formatString: 0
		lineageTag: f6db6181-ee84-4d65-81d7-c0430e4229a2
		summarizeBy: sum
		sourceColumn: Period_Sort

		annotation SummarizationSetBy = Automatic

	partition ___Cost_of_Training = m
		mode: import
		source =
				// 🕒 2026-03-23
				// # training/___Cost_of_Training.m
				// # Author: R. A. Carucci
				// # Purpose: Calculate training cost by delivery method with rolling 13-month window + calendar YTD.
				
				let
				    ReportMonth = pReportMonth,
				    Source = Excel.Workbook(
				        File.Contents("C:\Users\carucci_r\OneDrive - City of Hackensack\02_ETL_Scripts\Policy_Training_Monthly\output\policy_training_outputs.xlsx"),
				        null, true),
				    Tbl = Source{[Item = "Delivery_Cost_By_Month", Kind = "Sheet"]}[Data],
				    Promoted = Table.PromoteHeaders(Tbl, [PromoteAllScalars = true]),
				
				    // Strong types for wide table
				    TypedWide =
				        if Table.HasColumns(Promoted, {"Delivery_Type", "Total"})
				            then Table.TransformColumnTypes(
				                Promoted,
				                List.Combine(
				                    {{{"Delivery_Type", type text}, {"Total", type number}},
				                     List.Transform(
				                         List.RemoveItems(Table.ColumnNames(Promoted),
				                                          {"Delivery_Type", "Total"}),
				                         each{_, type number})}))
				            else Promoted,
				
				    // Rolling 13-month window: end = previous month, start = same month one year earlier
				    Today = DateTime.From(ReportMonth),
				    CurrentMonth = Date.Month(Today),
				    CurrentYear = Date.Year(Today),
				    EndMonth = if CurrentMonth = 1 then 12 else CurrentMonth - 1,
				    EndYear = if CurrentMonth = 1 then CurrentYear - 1 else CurrentYear,
				    StartMonth = EndMonth,
				    StartYear = EndYear - 1,
				    Report_Start_Date = #date(StartYear, StartMonth, 1),
				    Report_End_Date = #date(EndYear, EndMonth, 1),
				    MonthList = List.Generate(() => Report_Start_Date, each _ <= Report_End_Date, each Date.AddMonths(_, 1)),
				    PeriodLabelsMMYY = List.Transform(MonthList, each Text.PadStart(Text.From(Date.Month(_)), 2, "0") & "-" & Text.End(Text.From(Date.Year(_)), 2)),
				
				    // Calendar YTD through report month (fixes January reports and YTD cost cards that use Period_Sort)
				    YTDStart = #date(CurrentYear, 1, 1),
				    YTDEnd = #date(CurrentYear, CurrentMonth, 1),
				    YTDMonthList = List.Generate(() => YTDStart, each _ <= YTDEnd, each Date.AddMonths(_, 1)),
				    YTDLabels = List.Transform(
				        YTDMonthList,
				        each Text.PadStart(Text.From(Date.Month(_)), 2, "0") & "-" & Text.End(Text.From(Date.Year(_)), 2)),
				    AllPeriodLabels = List.Distinct(List.Combine({PeriodLabelsMMYY, YTDLabels})),
				
				    // Unpivot all month columns -> Period, Cost
				    MonthCols = List.Difference(Table.ColumnNames(TypedWide),
				                                {"Delivery_Type", "Total"}),
				    Unpivoted = Table.Unpivot(TypedWide, MonthCols, "Period", "Cost"),
				
				    // 13-month rolling window OR calendar YTD through pReportMonth (union)
				    Filtered = Table.SelectRows(Unpivoted, each List.Contains(AllPeriodLabels, [Period])),
				
				    // Add sort key so Period (MM-YY) sorts chronologically
				    WithSort = Table.AddColumn(
				        Filtered, "Period_Sort",
				        each let mm = Number.FromText(Text.Start([Period], 2)),
				        yy = Number.FromText(Text.End([Period], 2)),
				        yyyy = if yy < 70 then 2000 + yy else 1900 + yy in yyyy * 100 + mm,
				        Int64.Type),
				
				    // Final types
				    Final = Table.TransformColumnTypes(WithSort, {{"Delivery_Type", type text},
				                                                  {"Period", type text},
				                                                  {"Cost", type number},
				                                                  {"Period_Sort", Int64.Type}})
				                in Final

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

