table ___Traffic
	lineageTag: 529e55f2-9eb0-4b4b-82fa-cdca550257c0

	measure 'Parking Fees Formatted' =
			
			IF(
			    SELECTEDVALUE('___Traffic'[Tracked Items]) = "Parking Fees Collected",
			    FORMAT(SUM('___Traffic'[Current_Month_Value]), "Currency"),
			    FORMAT(SUM('Traffic'[Current_Month_Value]), "General Number")
			)
		lineageTag: 9cbf3a70-2bfc-49fd-bff6-6f8b9f7886f1

	measure 'Traffic Value Display' =
			
			VAR SelectedItem = SELECTEDVALUE('___Traffic'[Tracked Items])
			VAR IsCurrency = SELECTEDVALUE('___Traffic'[Is Currency])
			VAR CurrentValue = SELECTEDVALUE('___Traffic'[Value])
			RETURN
			SWITCH(
			    IsCurrency,
			    "Yes", FORMAT(CurrentValue, "$#,##0"),      // Currency format for parking fees
			    "No", FORMAT(CurrentValue, "#,##0"),        // Whole number format for others
			    FORMAT(CurrentValue, "#,##0")               // Default to whole numbers
			)
		lineageTag: 217145e5-91aa-4f28-91e8-c891de8cb1cb

	measure 'Traffic Value Currency Format' =
			
			VAR SelectedItem = SELECTEDVALUE('___Traffic'[Tracked Items])
			VAR CurrentValue = SELECTEDVALUE('___Traffic'[Value])
			RETURN
			IF(
			    SelectedItem = "Parking Fees Collected",
			    FORMAT(CurrentValue, "$#,##0"),             // Show as currency
			    FORMAT(CurrentValue, "#,##0")               // Show as whole number
			)
		lineageTag: a60cb2d5-d432-4f8a-bd13-1de72bcc3f85

	measure 'Traffic Subtitle' = ```
			
			"13-Month Overview (" & 'UI'[UI MonthRange 13m] & ")"
			
			```
		lineageTag: 53f514c3-6c6e-41f2-aba1-ce54c642704b

	measure 'Traffic Crashes Title' = ```
			
			"Motor Vehicle Accidents - Summary"
			
			```
		lineageTag: 0834b251-efdb-4987-95e9-5191f349b8be

	measure 'Traffic Crashes Subtitle' = ```
			
			"13-Month Overview (" & 'UI'[UI MonthRange 13m] & ")"
			
			```
		lineageTag: 7592df2c-8dbc-4e8b-9258-79c366135823

	column 'Tracked Items'
		dataType: string
		lineageTag: 417fa48c-603a-41b6-9b55-68623f5d4a66
		summarizeBy: none
		sourceColumn: Tracked Items

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: string
		lineageTag: b8e54761-a292-4527-8b95-8332b1553891
		summarizeBy: none
		sourceColumn: Period
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Is Currency'
		dataType: string
		lineageTag: 12850bda-3ca5-44bf-a659-ce5ce208a510
		summarizeBy: none
		sourceColumn: Is Currency

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: string
		lineageTag: 31637bf9-cf8e-4c1a-a05e-79746c021fcb
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: string
		lineageTag: 7358d3d3-b274-4585-b06a-22927cc00fd0
		summarizeBy: none
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	column 'Window Info'
		dataType: string
		lineageTag: 88e89f68-db48-4ff2-bafa-5a8da809ce46
		summarizeBy: none
		sourceColumn: Window Info

		annotation SummarizationSetBy = Automatic

	column 'Period Label'
		dataType: string
		lineageTag: 3f26c5c1-cfe0-42de-a283-b0d1620efa2f
		summarizeBy: none
		sourceColumn: Period Label

		annotation SummarizationSetBy = Automatic

	column 'Rolling Month'
		dataType: string
		lineageTag: afd5d019-8630-4504-b537-d3aed38f0090
		summarizeBy: none
		sourceColumn: Rolling Month

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: string
		lineageTag: 19fecd31-74b4-442b-bcd4-365fd79bb22f
		summarizeBy: none
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition ___Traffic = m
		mode: import
		source =
				// 🕒 2026-02-21-01-00-00 (EST)
				// # traffic/___Traffic.m
				// # Author: R. A. Carucci
				// # Purpose: Load Traffic Bureau monthly activity metrics from contribution workbook.
				
				let
				    ReportMonth = pReportMonth,
				    Source = Excel.Workbook(
				        File.Contents(
				            "C:\Users\carucci_r\OneDrive - City of Hackensack\Shared Folder\Compstat\Contributions\Traffic\Traffic_Monthly.xlsx"),
				        null, true),
				    _mom_traffic_Table = Source{[Item = "_mom_traffic", Kind = "Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(_mom_traffic_Table, {
				        {"Tracked Items", type text}, {"06-23", Int64.Type}, {"07-23", Int64.Type},
				        {"08-23", Int64.Type}, {"09-23", Int64.Type}, {"10-23", Int64.Type},
				        {"11-23", Int64.Type}, {"12-23", Int64.Type}, {"01-24", Int64.Type},
				        {"02-24", Int64.Type}, {"03-24", Int64.Type}, {"04-24", Int64.Type},
				        {"05-24", Int64.Type}, {"06-24", Int64.Type}, {"07-24", Int64.Type},
				        {"08-24", Int64.Type}, {"09-24", Int64.Type}, {"10-24", Int64.Type},
				        {"11-24", Int64.Type}, {"12-24", Int64.Type}, {"01-25", Int64.Type},
				        {"02-25", Int64.Type}, {"03-25", Int64.Type}, {"04-25", Int64.Type},
				        {"05-25", Int64.Type}, {"06-25", Int64.Type}, {"07-25", Int64.Type},
				        {"08-25", Int64.Type}, {"09-25", Int64.Type}, {"10-25", Int64.Type},
				        {"11-25", Int64.Type}, {"12-25", Int64.Type}, {"01-26", Int64.Type}
				    }),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [Tracked Items] <> "Grand Total"),
				
				    CurrentDate = DateTime.From(ReportMonth),
				    EndDate = Date.AddMonths(Date.StartOfMonth(DateTime.Date(CurrentDate)), -1),
				    StartDate = Date.AddMonths(EndDate, -12),
				
				    DateColumns = List.RemoveItems(Table.ColumnNames(#"Filtered Rows"), {"Tracked Items"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Filtered Rows", {"Tracked Items"}, "Period", "Value"),
				
				    #"Added Date Column" = Table.AddColumn(#"Unpivoted Columns", "Date", each
				        let
				            monthPart = Text.Start([Period], 2),
				            yearPart = "20" & Text.End([Period], 2),
				            fullDate = monthPart & "/01/" & yearPart
				        in
				            Date.From(fullDate)),
				
				    #"Filtered Rolling Window" = Table.SelectRows(#"Added Date Column",
				        each [Date] >= StartDate and [Date] <= EndDate),
				
				    #"Arrest Details Only" = Table.SelectRows(#"Filtered Rolling Window",
				        each [Tracked Items] <> "Total - Arrest(s)"),
				
				    #"Arrest Components" = Table.SelectRows(#"Arrest Details Only", each
				        [Tracked Items] = "Criminal Warrant Arrest" or
				        [Tracked Items] = "DUI Arrest" or
				        [Tracked Items] = "Self-Initiated Arrest" or
				        [Tracked Items] = "Motor Vehicle Warrant"),
				
				    #"Grouped Arrest Totals" = Table.Group(#"Arrest Components", {"Period"},
				        {{"Calculated Total", each List.Sum([Value]), type number}}),
				
				    #"Added Corrected Totals" = Table.AddColumn(#"Grouped Arrest Totals", "Tracked Items",
				        each "Total - Arrest(s)"),
				
				    #"Renamed Total Value" = Table.RenameColumns(#"Added Corrected Totals",
				        {{"Calculated Total", "Value"}}),
				
				    #"Reordered Total Columns" = Table.ReorderColumns(#"Renamed Total Value",
				        {"Tracked Items", "Period", "Value"}),
				
				    #"Added Date to Totals" = Table.AddColumn(#"Reordered Total Columns", "Date", each
				        let
				            monthPart = Text.Start([Period], 2),
				            yearPart = "20" & Text.End([Period], 2),
				            fullDate = monthPart & "/01/" & yearPart
				        in
				            Date.From(fullDate)),
				
				    #"Combined Data" = Table.Combine({#"Arrest Details Only", #"Added Date to Totals"}),
				
				    #"Added Currency Flag" = Table.AddColumn(#"Combined Data", "Is Currency", each
				        if [Tracked Items] = "Parking Fees Collected" then "Yes" else "No"),
				
				    #"Added Window Info" = Table.AddColumn(#"Added Currency Flag", "Window Info", each
				        "Rolling 13-Month Window: " &
				        Date.ToText(StartDate, "MMM yyyy") & " to " &
				        Date.ToText(EndDate, "MMM yyyy")),
				
				    #"Added Sort Order" = Table.AddColumn(#"Added Window Info", "Sort Order", each
				        Date.Year([Date]) * 100 + Date.Month([Date])),
				
				    #"Added Period Label" = Table.AddColumn(#"Added Sort Order", "Period Label", each
				        Date.ToText([Date], "MMM yyyy")),
				
				    #"Added Rolling Month" = Table.AddColumn(#"Added Period Label", "Rolling Month", each
				        let
				            MonthDiff = ((Date.Year([Date]) - Date.Year(StartDate)) * 12) +
				                       (Date.Month([Date]) - Date.Month(StartDate)) + 1
				        in
				            MonthDiff),
				
				    #"Updated Values" = Table.AddColumn(#"Added Rolling Month", "Final Value", each
				        if [Tracked Items] = "Parking Fees Collected" then
				            [Value]
				        else
				            Number.RoundUp([Value], 0)),
				
				    #"Removed Original" = Table.RemoveColumns(#"Updated Values", {"Value"}),
				    #"Renamed Value" = Table.RenameColumns(#"Removed Original", {{"Final Value", "Value"}})
				in
				    #"Renamed Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

