// Name this query: DimEventType
let
    Source = #table(
        {"EventType"},
        {
            {"Show of Force"},
            {"Use of Force"},
            {"Vehicle Pursuit"}
        }
    ),
    Typed = Table.TransformColumnTypes(Source, {{"EventType", type text}})
in
    Typed