// ==============================================================================
// RESPONSE TIMES M CODE - LOADS FROM MONTHLY ETL OUTPUT FILES
// Query Name: response_time_calculator
// ==============================================================================
// VERSION: 2.1.0
// UPDATED: 2026-01-14
//
// DATA SOURCE: Monthly CSV files generated by response_time_monthly_generator.py
// COVERAGE: December 2024 through December 2025 (13 months)
//
// FILE STRUCTURE:
// PowerBI_Date/Backfill/YYYY_MM/response_time/YYYY_MM_Average_Response_Times__Values_are_in_mmss.csv
// ==============================================================================

let
    // ========================================================================
    // CONFIGURATION
    // ========================================================================

    BasePath = "C:\Users\carucci_r\OneDrive - City of Hackensack\PowerBI_Date\Backfill\",

    // Target months (folder names)
    TargetMonths = {
        "2024_12",
        "2025_01", "2025_02", "2025_03", "2025_04", "2025_05", "2025_06",
        "2025_07", "2025_08", "2025_09", "2025_10", "2025_11", "2025_12"
    },

    // ========================================================================
    // HELPER FUNCTION: Load a single month's CSV file
    // ========================================================================

    LoadMonthlyCSV = (monthFolder as text) as table =>
        let
            FilePath = BasePath & monthFolder & "\response_time\" & monthFolder & "_Average_Response_Times__Values_are_in_mmss.csv",
            RawData = try Csv.Document(
                File.Contents(FilePath),
                [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
            ) otherwise null,

            Result = if RawData <> null then
                let
                    WithHeaders = Table.PromoteHeaders(RawData, [PromoteAllScalars=true]),
                    Renamed = Table.RenameColumns(
                        WithHeaders,
                        {
                            {"Response Type", "Response_Type"},
                            {"First Response_Time_MMSS", "Response_Time_MMSS"}
                        },
                        MissingField.Ignore
                    )
                in
                    Renamed
            else
                #table({"Response_Type", "MM-YY", "Response_Time_MMSS"}, {})
        in
            Result,

    // ========================================================================
    // LOAD ALL MONTHLY FILES
    // ========================================================================

    AllMonthlyData = List.Transform(TargetMonths, each LoadMonthlyCSV(_)),
    Combined = Table.Combine(AllMonthlyData),

    // ========================================================================
    // ADD CALCULATED COLUMNS
    // ========================================================================

    // Calculate Average_Response_Time from MM:SS format
    WithAvgTime = Table.AddColumn(
        Combined,
        "Average_Response_Time",
        each let
            timeStr = Text.Trim(Text.From([Response_Time_MMSS])),
            parts = Text.Split(timeStr, ":"),
            minutes = if List.Count(parts) >= 2 then
                let
                    mins = try Number.From(parts{0}) otherwise 0,
                    secs = try Number.From(parts{1}) otherwise 0,
                    totalMins = mins + (secs / 60.0)
                in
                    totalMins
            else
                null
        in
            minutes,
        type number
    ),

    // Add YearMonth from MM-YY (e.g., "12-24" -> "2024-12")
    WithYearMonth = Table.AddColumn(
        WithAvgTime,
        "YearMonth",
        each let
            mmYY = Text.Trim(Text.From([#"MM-YY"])),
            parts = Text.Split(mmYY, "-"),
            yearMonth = if List.Count(parts) >= 2 then
                let
                    mm = parts{0},
                    yy = "20" & parts{1},
                    yearMonthStr = yy & "-" & Text.PadStart(mm, 2, "0")
                in
                    yearMonthStr
            else
                null
        in
            yearMonth,
        type text
    ),

    // Add Date_Sort_Key - proper date type for sorting (first day of month)
    WithDateKey = Table.AddColumn(
        WithYearMonth,
        "Date_Sort_Key",
        each try Date.FromText([YearMonth] & "-01") otherwise null,
        type date
    ),

    // ========================================================================
    // ADD DAX COMPATIBILITY COLUMNS
    // ========================================================================

    WithSummaryType = Table.AddColumn(WithDateKey, "Summary_Type", each "Response_Type", type text),
    WithCategory = Table.AddColumn(WithSummaryType, "Category", each [Response_Type], type text),
    WithDate = Table.AddColumn(WithCategory, "Date", each [Date_Sort_Key], type date),

    // ========================================================================
    // SET COLUMN TYPES
    // ========================================================================

    Typed = Table.TransformColumnTypes(
        WithDate,
        {
            {"Response_Type", type text},
            {"Response_Time_MMSS", type text},
            {"MM-YY", type text},
            {"YearMonth", type text},
            {"Date_Sort_Key", type date},
            {"Date", type date},
            {"Average_Response_Time", type number},
            {"Summary_Type", type text},
            {"Category", type text}
        },
        "en-US"
    ),

    // ========================================================================
    // SELECT AND ORDER FINAL COLUMNS
    // ========================================================================

    Result = Table.SelectColumns(
        Typed,
        {
            "YearMonth",
            "Date_Sort_Key",
            "Date",
            "Response_Type",
            "Summary_Type",
            "Category",
            "Average_Response_Time",
            "Response_Time_MMSS",
            "MM-YY"
        }
    ),

    FinalSorted = Table.Sort(Result, {{"Date_Sort_Key", Order.Ascending}, {"Response_Type", Order.Ascending}})

in
    FinalSorted

// ==============================================================================
// OUTPUT COLUMNS:
// - YearMonth (text): "2024-12", "2025-01", etc.
// - Date_Sort_Key (date): Date type for sorting (first day of month)
// - Date (date): Alias for Date_Sort_Key (DAX compatibility)
// - Response_Type (text): "Emergency", "Routine", "Urgent"
// - Summary_Type (text): "Response_Type" (DAX compatibility)
// - Category (text): Same as Response_Type (DAX compatibility)
// - Average_Response_Time (number): Decimal minutes (e.g., 2.65 = 2:39)
// - Response_Time_MMSS (text): Original MM:SS format (e.g., "2:39")
// - MM-YY (text): Month-Year format (e.g., "12-24")
//
// DATA COVERAGE: December 2024 through December 2025 (13 months)
//
// ETL SCRIPT: response_time_monthly_generator.py
// ==============================================================================
